### ISSUE TITLE
Koa middleware calling `next()` + /new redirect

### ISSUE THREAD

**Issue by leebenson** [graphcool/graphql-playground#139]
Really nice project. I'd love to swap out GraphiQL for this in [ReactQL](https://github.com/reactql/cli).

I'm running into an issue with the Koa-flavoured middleware.

Currently, I have [this code](https://github.com/reactql/kit/blob/master/kit/entry/server.js#L354-L360) to instantiate GraphiQL with Koa:

```js
import { graphiqlKoa } from 'apollo-server-koa';

// ...

router.get(
  graphiQLEndpoint,  // <-- coming from ReactQL userland
  graphiqlKoa({
    endpointURL: config.graphQLEndpoint,  // <-- also set by the user
  }),
);
```

Looking at the Playground readme, it seems that the Koa middleware should be a drop-in placement; save for changing `endpointURL` -> `endpointUrl`, the syntax is identical:

```js
router.get(
  graphiQLEndpoint,
  playground({
    endpointUrl: config.graphQLEndpoint,
  }),
);
```

However, instead of getting the Playground UI, I actually get a 404. Looking at the [source](https://github.com/graphcool/graphql-playground/blob/master/packages/graphql-playground/src/middleware/koa.ts), it seems to be because you're awaiting the `next()` middleware in the chain.

In the case of koa-router, calling `next()` on a route means that the route didn't 'finish', which is then caught by an upstream handler in ReactQL that handles the 404.

I can _kinda_ fix it by monkey patching `next` with a blank function:

```js
router.use(graphiQLEndpoint, ctx => (
  playground({ endpointUrl: config.graphQLEndpoint })(ctx, () => {})
));
```

... which works for a brief second, but then Playground redirects from `/playground` to `/new`:

<img width="1024" alt="screen shot 2017-09-27 at 16 56 17" src="https://user-images.githubusercontent.com/719722/30923846-ef3053ec-a3a4-11e7-8b03-aeb9811bf2be.png">

Which is due to this code at http://cdn.jsdelivr.net/npm/graphql-playground@0.1.18/build/static/js/main.js

<img width="1408" alt="screen shot 2017-09-27 at 16 58 29" src="https://user-images.githubusercontent.com/719722/30923929-28dc8872-a3a5-11e7-91db-9b647c717c87.png">

So, it seems possibly there's a couple of things here:

1. Making the Koa middleware conform to the expectation that the route will 'terminate', and avoid calling the next in the chain.

2. Enabling Playground to be hosted at a path, with further navigation respecting the path prefix.

**Comment by DevanB** [comment]
This is happening in Express for me as well. So not limited to Koa, possibly.

**Comment by leebenson** [comment]
Looks like `/new` is setting up a new view session where one doesn't already exist.

For example, the demo here at https://www.graphqlbin.com/RVIn remains on that route throughout. But going to https://www.graphqlbin.com redirects to -> https://www.graphqlbin.com/new

It'd be nice to have a 'prefix' option that is set automatically inside the HTML that's rendered (by looking at, say, Koa's `ctx.request.url`, and passing that through)

```html
window.addEventListener('load', function(event) {
  GraphQLPlayground.init(document.getElementById('root'), {
    endpointUrl: "/graphql",
    undefined
  })
})
```

... which could inform the compiled Playground bundle to push to `prefix + '/new'` instead of a static '/new'.

**Comment by overra** [comment]
What's happening is we're mounting the middleware on `/playground` and because of the routing below it thinks that 'playground' is the id of a session.  I think adding a [basename](https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string) prop to `<BrowserRouter>` should fix this. 

https://github.com/graphcool/graphql-playground/blob/master/packages/graphql-playground/src/components/Root.tsx#L8-L13

**Comment by DevanB** [comment]
Also - When you mount the playground at `/` it breaks all other routes, obviously.

**Comment by timsuchanek** [comment]
Just published a new version which should fix this issue. Reopen if this is still a problem

**Comment by DevanB** [comment]
@timsuchanek Just an FYI - I see the new version (1.0.2) in npm, but not in the [Releases](https://github.com/graphcool/graphql-playground/releases) tab here in GitHub.

Thanks for working on this! :)

**Comment by curtisallen** [comment]
@timsuchanek just tried `1.0.3` with express middleware and still seeing the same behavior.
