### ISSUE TITLE
Full of bugs in 1.3.8

### ISSUE THREAD

**Issue by gijo-varghese** [graphcool/graphql-playground#361]
Ok, So I recently upgraded to the latest version (`1.3.8`) of Playground "graphql-playground-middleware-express". Buts its full of bugs. Here are some of the issues I found:

- History not working. After reloading the playground, the history is gone. I can't even access it from "history" button
- Unable to turn on "Auto reload schema", previously there was a settings button where I can change this. Now it's a config file. Where are the docs for it?
- Subscriptions not working!

A feature request: Can we change the font size of the result? the font size/line height is little high so that I can only see a little 

For now, I have downgraded to `1.2.0`

**Comment by marktani** [comment]
Hey @gijo-varghese, sorry to hear about your experience! In the latest version the history is fixed 🙂 

We'll also [implement reloading via CMD+R](https://github.com/graphcool/graphql-playground/issues/180). There's also already a feature request for [changing the font size](https://github.com/graphcool/graphql-playground/issues/291).

I'm closing this issue, could you please check if subscriptions work for you in the latest version? They work for me.

**Comment by gijo-varghese** [comment]
@marktani ok. Great! Everything except subscriptions is working. I don't know what wrong with subscriptions!. Below is the code that I'm using:
```
module.exports = {
  graphqlExpress: graphqlExpress({
    schema,
    context: {},
    subscriptionsEndpoint: "ws://localhost:" + config.port + "/subscriptions"
  }),
  graphiqlExpress: graphiqlExpress({
    endpointURL: "/graphql",
    subscriptionsEndpoint: "ws://localhost:" + config.port + "/subscriptions"
  }),
  expressPlayground: expressPlayground({
    endpoint: "/graphql",
    subscriptionEndpoint: "ws://localhost:" + config.port + "/subscriptions"
  }),
  start_server: app => {
    const webSocketServer = createServer(app);
    webSocketServer.listen(config.port, () => {
      console.log("GraphQL server started!");
      new SubscriptionServer(
        {
          execute,
          subscribe,
          schema
        },
        {
          server: webSocketServer,
          path: "/subscriptions"
        }
      );
    });
  }
};
```

**Comment by schickling** [comment]
@gijo-varghese can you give subscriptions another try in the newest version? Here is a working example for subscriptions: https://github.com/graphcool/graphql-yoga/tree/master/examples/subscriptions

**Comment by gijo-varghese** [comment]
@schickling tried. Still not working!. I'm giving up. Also contains many other bugs in the new version!
